### ISSUE TITLE
Build Failed on Raspberry Pi Compute Module

### ISSUE THREAD

**Issue by JihunDev** [OpenVoiceOS/VocalFusionDriver#2]
I used raspberry pi compute module 4 and it looks like below
> 2022-01-28-raspios-bullseye-arm64
> Linux kernel 5.10.92

The compute model I use is a model with 2GB RAM and 8GB eMMC and a model without 1GB RAM and eMMC.

When `make all`, the following error occurs.
```
pi@raspberrypi:~/VocalFusionDriver/driver $ make all
make -C /lib/modules/5.10.92-v8+/build M=/home/pi/VocalFusionDriver/driver modules
make[1]: Entering directory '/usr/lib/modules/5.10.92-v8+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/5.10.92-v8+/build'
make: *** [Makefile:6: all] Error 2
```

**Comment by j1nx** [comment]
Do you have the kernel headers package installed for your kernel?

**Comment by JihunDev** [comment]
How do I install the kernel headers package?

**Comment by j1nx** [comment]
Depends a bit on which distro you are running.

You can try "sudo apt-get install raspberrypi-kernel-headers" if you're running raspbian.

otherwise you have to google a bit how to do it for your running distrobution.

**Comment by JihunDev** [comment]
I installed raspberrypi-kernel-headers, but I get an error.

```
pi@raspberrypi:~/VocalFusionDriver/driver $ make all
make -C /lib/modules/5.10.92-v8+/build M=/home/pi/VocalFusionDriver/driver modules
make[1]: Entering directory '/usr/lib/modules/5.10.92-v8+/build'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/lib/modules/5.10.92-v8+/build'
make: *** [Makefile:6: all] Error 2
```

**Comment by j1nx** [comment]
Strange! To be honest. I have no clue...

@NeonDaniel How do you include these drivers within the NEON MArk2 image?

**Comment by NeonDaniel** [comment]
About the same, there's some extra logic here to pick the right kernel since I do it all in chroot:
https://github.com/NeonGeckoCom/neon_debos/blob/main/scripts/20-setup-sj201.sh

I do recall the something didn't work with qemu, I think until I built the kernel from source instead of using one from raspberry pi.. There are references to the kernel I use in that same debos repository.

**Comment by JihunDev** [comment]
@NeonDaniel The version of Raspbian I used is 2022-09-06, and the Linux Kernel version 5.15.61 was used. In the link, the kernel was also confirmed to be the same version.

**Comment by JihunDev** [comment]
I tried reinstalling using the updated version of [v5.8.0 release](https://github.com/xmos/vocalfusion-rpi-setup/blob/master/README.md) in XMOS and it was successfully installed.
